/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	__asm("SVC #0x08");

	//register uint32_t data __asm("r0");
	uint32_t data;
	__asm volatile("MOV %0,R0": "=r"(data) ::);
	printf("Data : %ld",data);

    /* Loop forever */
	for(;;);
}

__attribute__ ((naked)) void SVC_Handler(void){
	//1. Get value of the MSP
	__asm("MRS R0,MSP");
	__asm("B SVC_Handler_c");
}

void SVC_Handler_c(uint32_t *pBaseOfStackFrame){
	printf("In SVC handler\n");

	uint8_t *pReturn_addr = (uint8_t*)pBaseOfStackFrame[6];

	//2. Decrement the return address by 2 to point to
	//opcode of the svc instruction in the program memory
	pReturn_addr-=2;

	//3. extract the SVC number (LSB of the opcode)
	uint8_t svc_number = *pReturn_addr;

	svc_number+=4;

	pBaseOfStackFrame[0] = svc_number;
}
