/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define TIMER2_IRQNO 28
#define I2C1EV_IRQNO 31

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint32_t *pNVIC_IPRBase = (uint32_t*)0xE000E400;
uint32_t *pNVIC_ISERBase = (uint32_t*)0xE000E100;
uint32_t *pNVIC_ISPRBase = (uint32_t*)0xE000E200;

void configure_irq_priority(uint8_t irq_no, uint8_t priority_value){
	//Find out X in IPRX
	uint8_t iprx = irq_no / 4;
	uint32_t *pIPR = pNVIC_IPRBase + iprx;
	//Position in IPRX
	uint8_t pos = ((irq_no % 4) * 8);
	//Configure priority
	*pIPR &= ~(0xFF << pos); //clear
	*pIPR |= (priority_value << pos);
}

int main(void)
{
	//Configure priority of IRQs
	configure_irq_priority(TIMER2_IRQNO, 0x80);
	configure_irq_priority(I2C1EV_IRQNO, 0x80);

	//Set pending IRQ bits
	*pNVIC_ISPRBase |= (1<<TIMER2_IRQNO);

	//Enable IRQs
	*pNVIC_ISERBase |= (1<<TIMER2_IRQNO);
	*pNVIC_ISERBase |= (1<<I2C1EV_IRQNO);

    /* Loop forever */
	for(;;);
}

//ISRs
void TIM2_IRQHandler(void){
	printf("TIM2_IRQHandler\n");
	*pNVIC_ISPRBase |= (1<<I2C1EV_IRQNO);
	while(1);
}

void I2C1_EV_IRQHandler(void){
	printf("I2C1_EV_IRQHandler\n");
}
